[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["asf_progress_indicators"]

[project]
name = "asf_progress_indicators"
version = "0.1.0"
description = "A repo to manage the data analysis for tracking the A Sustainable Future mission progress indicators."
authors = [{ name = "Nesta" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "boto3>=1.38.31",
    "matplotlib>=3.10.3",
    "openpyxl>=3.1.5",
    "pandas>=2.2.0",
    "requests>=2.32.3",
    "asf_levies_model @ git+https://github.com/nestauk/asf_levies_model.git",
    "python-calamine>=0.3.2",
    "statsmodels>=0.14.5",
]

[project.urls]
repository = "https://github.com/nestauk/asf_progress_indicators"
issues = "https://github.com/nestauk/asf_progress_indicators/issues"

[dependency-groups]
dev = ["ipykernel", "jupytext", "ruff", "pre-commit"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "ANN", # flake8-annotations
    "B",   # flake8-bugbear: Likely bugs
    "C",   # flake8-comprehensions and mccabe complexity
    "D",   # pydocstyle: Docstring conventions
    "E",   # pycodestyle: Errors (default)
    "F",   # pyflakes: Linter
    "I",   # isort
    "N",   # pep8-naming: Naming conventions
    "W",   # pycodestyle: Warnings (default)
]
ignore = [
    "D100", # Warns about missing module-level docstrings
    "S101", # Warns about assert being removed when compiled
    "D205", # Warns about 1 blank line being required between summary line and description in docstring
]

[tool.ruff.lint.isort]
known-first-party = ["asf_progress_indicators"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "E402", "D104"]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
